### ISSUE TITLE
Standardize a package.json line for linter forks

### ISSUE THREAD

**Issue by btkostner** [standard/standard-engine#196]
Right now we have a lot of plugins built around standard (and standard-engine). Sadly, most of these plugins use a hard coded list of forks for customizing. This makes it extremely hard to use a company or personal fork of standard, but still have all of the plugin support we love.

Standard engine should document a `package.json` key to identify a `standard-engine` compatible linting package. [`linter-js-standard-engine`](https://github.com/gustavnikolaj/linter-js-standard-engine#usage) already documents a `standard-engine` key that is refered to in this project's readme, so I recommend just taking that and putting it in the `standard-engine` `README.md`.

**Comment by feross** [comment]
@btkostner This is a great idea. If you send a PR, I'm happy to merge it!
