### ISSUE TITLE
Publish 12.0.1

### ISSUE THREAD

**Issue by LinusU** [standard/standard-engine#221]
ping @feross, @watson, @mafintosh, @maxogden, @Flet 

Could someone add me to the npm package so that I can run `npm publish`? ❤️

**Comment by toddbluhm** [comment]
Yeah, it would be great to get this published before https://github.com/standard/standard-engine/pull/214 gets merged in causing a major version bump.

**Comment by Flet** [comment]
@linusU Sorry for the delays, just added you as an npm maintainer!

**Comment by LinusU** [comment]
12.0.1 is now published 🚀 

Thanks @Flet!
