### ISSUE TITLE
Move APIs to Promise

### ISSUE THREAD

**Issue by Divlo** [standard/standard-engine#249]
Instead of having sync or callback versions of our [APIs](https://github.com/standard/standard-engine#api-usage), we could migrate them to Promises.
By doing this, it makes #234 simpler to solve, as the "new" ESLint class API use Promises. 

We will remove `Linter.lintTextSync` method.

**Note:** It is a **BREAKING CHANGE**

**Comment by voxpelli** [comment]
An extra, probably needless, clarificaruib: We will probably mainly do this through `async` / `await` rather than creating Promises directly ourselves 👍
