### ISSUE TITLE
Generate and publish types

### ISSUE THREAD

**Issue by voxpelli** [standard/standard-engine#279]
As we're pretty much typed now, I think we should generate and publish types when we publish `15.0.0`.

This would require a setup similar to: https://github.com/voxpelli/pony-cause/blob/1a93b683ef5843ca43a67d1953460863372f4c73/package.json#L18-L20

**Comment by Divlo** [comment]
If we do so, we might deprecate this package: https://www.npmjs.com/package/@types/standard-engine
Source: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/standard-engine

**Comment by voxpelli** [comment]
@Divlo Which would be great, as else it would need updating as well to be usable with the new version 😝
